import NavBar from "@/components/navbar/NavBar";
import NavItem from "@/components/navbar/NavItem";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "YBS - Management Portal",
    description: "Generated by create next app",
    icons: { icon: "/favicon.ico" }
};

const NavItems = () => {
    return (
        <>
            <NavItem id="accounts" name="Accounts" />
            <NavItem id="companies" name="Companies" />
            <NavItem id="members" name="Members" />
            <NavItem id="mem-packs" name="Membership Packages" />
        </>
    )
}

export default function AdminLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <main className="w-screen">
            <NavBar><NavItems /></NavBar>
            {children}
        </main>
    );
}
