import { Metadata } from "next";
import Navbar from "@/components/Navbar";
import NavItem from "@/components/NavItem";

const Navlist = () => {
    return (
        <>
            <NavItem id="accounts" href="/admin/accounts" name="Accounts" />
            <NavItem id="companies" href="/admin/companies" name="Companies" />
            <NavItem id="members" href="/admin/members" name="Members" />
            <NavItem id="mem-packs" href="/admin/membership-packages" name="Membership Packages" />
        </>
    )
}

export const metadata: Metadata = {
    title: "YBS - Admin Portal",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div id="body-content" className="flex w-screen overflow-hidden">
            <div id="navbar" className="w-1/5">
                <Navbar>
                    <Navlist />
                </Navbar>
            </div>
            <main className="w-4/5">{children}</main>
        </div>
    );
}
